export const ONGOING_MATCH = 'ONGOING_MATCH'
export const SUCCESS_MATCH = 'SUCCESS_MATCH'
export const ERROR_MATCH = 'ERROR_MATCH'
export const REMOVE_MATCH = 'REMOVE_MATCH'

export const ONGOING_CONVERSATION = 'ONGOING_CONVERSATION'
export const SUCCESS_CONVERSATION = 'SUCCESS_CONVERSATION'
export const ERROR_CONVERSATION = 'ERROR_CONVERSATION'
export const REMOVE_CONVERSATION = 'REMOVE_CONVERSATION'

export const ONGOING_USER = 'ONGOING_USER'
export const SUCCESS_USER = 'SUCCESS_USER'
export const ERROR_USER = 'ERROR_USER'